# Generated by Django 3.2.4 on 2021-11-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='measurement',
        ),
    ]
