# Generated by Django 4.2.7 on 2023-11-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_stock_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Dry goods', 'Dry goods'), ('Vegetable', 'Vegetables'), ('Meat', 'Meat'), ('Others', 'Others')], max_length=19, null=True),
        ),
    ]
